package com.joom.smuggler

import android.os.Parcel
import android.os.Parcelable

interface AutoParcelable : Parcelable {
  override fun writeToParcel(parcel: Parcel, flags: Int) {
    throw UnsupportedOperationException("This method will never be used in runtime. The real implementation will be generated by smuggler plugin.")
  }

  override fun describeContents(): Int {
    throw UnsupportedOperationException("This method will never be used in runtime. The real implementation will be generated by smuggler plugin.")
  }
}
