package io.mironov.smuggler;

import android.os.Parcelable;

public final class SmugglerFactory {
  public static <S extends Smuggled> Parcelable.Creator<S> creator(final Class<S> clazz) {
    throw new UnsupportedOperationException("This method will never be used in runtime. The real implementation will be generated by smuggler plugin.");
  }
}
