package io.mironov.smuggler

import android.os.Parcel
import android.os.Parcelable

interface Smuggled : Parcelable {
  companion object {
    fun <S : Smuggled> creator(clazz: Class<S>): Parcelable.Creator<S> {
      return SmugglerFactory.creator(clazz)
    }

    inline fun <reified S : Smuggled> creator(): Parcelable.Creator<S> {
      return creator(S::class.java)
    }
  }

  override fun writeToParcel(parcel: Parcel, flags: Int) {
    throw UnsupportedOperationException("This method will never be used in runtime. The real implementation will be generated by smuggler plugin.")
  }

  override fun describeContents(): Int {
    throw UnsupportedOperationException("This method will never be used in runtime. The real implementation will be generated by smuggler plugin.")
  }
}
